baseURL = 'https://example.org/'
languageCode = 'es-es'
title = 'Silencio en la Sala'

[menus]
[[menus.main]]
name = 'POEMAS'
pageRef = '/poemas'
weight = 1
[[menus.main]]
name = 'HAIKUS'
pageRef = '/haikus'
weight = 3
[[menus.main]]
name = 'RELATOS'
pageRef = '/relatos'
weight = 2
[[menus.main]]
name = 'ENREDOS'
pageRef = '/enredos'
weight = 4


[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
