baseURL = 'https://example.org/'
languageCode = 'es-es'
title = 'Silencio en la Sala'

[menus]
[[menus.main]]
name = 'Poemas'
pageRef = '/poemas'
weight = 20
[[menus.main]]
name = 'Haikus'
pageRef = '/haikus'
weight = 20
[[menus.main]]
name = 'Microrelatos'
pageRef = '/micro-relatos'
weight = 20


[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
